---
title: "Homework 7 Group"
author: 
  - Gabe Gress
  - Minyue Hu
  - Tina Dantono
  - Kristin West
output:
  pdf_document:
    fig_height: 5
    fig_width: 5
    df_print: tibble
  html_document:
    df_print: paged
date: 'Due: Thursday October 29'
---

```{r,echo=TRUE}

library(RSQLite)
library(dplyr)
library(stringr)

setwd("./")
headers <- read.csv(file="./arxiv-dataset.csv")
names(headers) <- c("X", "ID", "Submitter", "Authors", "Title", "Comments", "JournalRef", "DOI", "ReportNo", "Categories", "License", "Abstract", "Versions", "UpdateDate", "AuthorsParsed")
yearsarx <- sapply(headers$ID,as.character)
yearsarx <- str_extract(yearsarx, pattern="(\\d{4})")
datesarx <- as.Date(paste(yearsarx,"01",sep=""), "%y%m%d")

seconddata <- read.csv(file="./Colleges_and_Universities.csv")

parsepythonlist <- function(pylist){
  
l <- pylist

l1 <- str_match(pattern = "(?<=\\[).*(?=\\])",string=l)
l1 = paste("list(",l1,")", sep="")
l2 <- gsub("\\[", "c(", l1, perl=TRUE)
l3 <- gsub("\\]", ")", l2, perl=TRUE)

pylist <- eval(parse(text = l3)) 

return(data.frame(matrix(unlist(pylist), nrow=length(pylist), byrow=T)))

}

#headers$AuthorsParsed = sapply(headers$AuthorsParsed,parsepythonlist)

#dfauthors <- data.frame(matrix(unlist(headers$AuthorsParsed), nrow=length(headers$AuthorsParsed), byrow=T))

```

```{r,echo=TRUE}


arxivtable <- dbConnect(SQLite(), dbname = "arXivMetadata.sqlite")
if (!dbExistsTable(arxivtable, "arXiv")){
dbSendQuery(conn = arxivtable, "
CREATE TABLE arXiv (
X int NOT NULL,
ID text NOT NULL,
Submitter text,
Authors text,
Title text,
Comments text,
JournalRef text,
DOI text,
ReportNo text,
Categories text,
License text,
Abstract text,
Versions text,
UpdateDate text,
AuthorsParsed text,
PRIMARY KEY (X)
);
")
  
dbWriteTable(conn = arxivtable, name = "arXiv", headers, append = TRUE, row.names = FALSE)
  
}

if (!dbExistsTable(arxivtable, "ColUni")){
dbSendQuery(conn = arxivtable, "
CREATE TABLE ColUni (
OBJECTID int NOT NULL,
IPEDSID int NOT NULL,
NAME text NOT NULL,
ADDRESS text,
CITY text,
STATE text,
ZIP int,
TYPE int,
POPULATION int,
COUNTRY text,
LATITUDE text,
LONGITUDE text,
NAICS_CODE int,
NAICS_DESC text,
SOURCE text,
WEBSITE text,
PT_ENROLL int,
FT_ENROLL int,
TOT_ENROLL int,
TOT_EMP int,
PRIMARY KEY (OBJECTID)
);
")

dbWriteTable(conn = arxivtable, name = "ColUni", select(seconddata, OBJECTID,
IPEDSID,
NAME,
ADDRESS,
CITY,
STATE,
ZIP,
TYPE,
POPULATION,
COUNTRY,
LATITUDE,
LONGITUDE,
NAICS_CODE,
NAICS_DESC,
SOURCE,
WEBSITE,
PT_ENROLL,
FT_ENROLL,
TOT_ENROLL,
TOT_EMP), append = TRUE, row.names = FALSE)
}
```

```{r,echo=TRUE}
query <- "
SELECT Authors, Title, Categories
FROM arXiv
WHERE Authors BETWEEN 'A' and 'M'
ORDER BY Categories, Authors"
res <- dbSendQuery(arxivtable, query)
dbFetch(res, -1)

dbClearResult(res)
dbDisconnect(arxivtable)
```